language: cpp
matrix:
  include:
  - os: linux
    compiler: gcc
    dist: focal
    sudo: required
    install: "./travis-install.sh"
    script: make test
  - if: tag IS NOT present
    os: osx
    compiler: clang
    install: "./travis-install.sh"
    script: make xcode/test
  - if: tag IS present
    env: >
      BOOST_ROOT="${TRAVIS_BUILD_DIR}/thirdparty/src/boost_1_75_0"
      BUILD_UNIVERSAL=1
      RIME_PLUGINS="${RIME_BUNDLED_PLUGINS}"
    os: osx
    osx_image: xcode12u
    compiler: clang
    install: "./travis-install.sh"
    script:
    - make xcode/test xcode/dist RIME_PLUGINS=
    - |
      zip -r rime-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.zip \
      dist thirdparty/bin thirdparty/share \
      -x '*/curl.exe'
    - make xcode/test xcode/dist
    - |
      zip -r rime-with-plugins-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.zip \
      dist thirdparty/bin thirdparty/share \
      -x '*/curl.exe'
    deploy:
      provider: releases
      api_key:
        secure: Le2PfdrOqVmk5c1Eu/q9fvLGG1WZz5SuIXw0LVTqWn8cPCJvvsh9/RsjKx59uI0rxs/sJnbsCnPSaiveY5i51Jy7apkqtysUfglr+2CjgyXY5s7qBWiZ60/j2V5CDkk+Q/PSB/GXcVxHQWPh6X1M75GWa9b+4COKJX3Kh/FO0rM=
      file:
        - "rime-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.zip"
        - "rime-with-plugins-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.zip"
      skip_cleanup: true
      name: librime ${TRAVIS_TAG}
      body: 'chore(release): ${TRAVIS_TAG} :tada:'
      draft: true
      on:
        repo: rime/librime
        tags: true
