language: cpp

matrix:
  include:
    - os: osx
      compiler: clang
      #osx_image: xcode6.1  # default: xcode6.1 (SDK min:10.9)
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required

before_install:
  - is_linux() { [[ "$TRAVIS_OS_NAME" == linux ]]; }
  - is_osx() { [[ "$TRAVIS_OS_NAME" == osx ]]; }

  - if is_linux; then sudo apt-get update; fi
  - if is_linux; then sudo apt-get install doxygen libboost-filesystem-dev libboost-locale-dev libboost-regex-dev libboost-signals-dev libboost-system-dev libgoogle-glog-dev libleveldb-dev libmarisa-dev libyaml-cpp-dev -y; fi
  - if is_linux; then make thirdparty/gtest; fi
  - if is_linux; then make -C thirdparty/src/opencc build; fi
  - if is_linux; then sudo make -C thirdparty/src/opencc install; fi

  - if is_osx; then make -f Makefile.xcode thirdparty; fi

script:
  - if is_linux; then make debug; fi
  - if is_linux; then pushd debug-build/test; fi
  - if is_linux; then ./rime_test; fi
  - if is_linux; then popd; fi

  - if is_osx; then make -f Makefile.xcode debug; fi
  - if is_osx; then pushd xdebug/test; fi
  - if is_osx; then ./Debug/rime_test; fi
  - if is_osx; then popd; fi
