skip_tags: true
clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

version: '{branch} build {build}'
image: Visual Studio 2015

environment:
  BOOST_ROOT: C:\Libraries\libboost
  CL: /Zc:threadSafeInit-

cache:
  - thirdparty.cached -> appveyor.install.bat
  - thirdparty\bin -> appveyor.install.bat
  - thirdparty\data -> appveyor.install.bat
  - thirdparty\include -> appveyor.install.bat
  - thirdparty\lib -> appveyor.install.bat
  - C:\Libraries\libboost -> appveyor.install.bat

init:
  - git --version
  - cmake --version
  - git config --global core.autocrlf true

install:
  - .\appveyor.install.bat

build_script:
  - .\build.bat test

after_build:
  - 7z a rime.zip build\bin build\lib build\include thirdparty\data\opencc
  - dir build /s

before_test:
  - copy /y build\lib\Release\rime.dll build\test\Release

test_script:
  - cd build\test
  - .\Release\rime_test.exe

artifacts:
  - path: rime.zip
    name: Binaries, includes and OpenCC data
