name: Release CI

on:
  push:
    tags:
      - '[0-9]+.*'

jobs:
  linux:
    uses: ./.github/workflows/linux-build.yml

  macos:
    uses: ./.github/workflows/macos-build.yml
    with:
      build_variant: '-universal'
      rime_plugins: rime/librime-charcode hchunhui/librime-lua lotem/librime-octagram

  windows:
    uses: ./.github/workflows/windows-build.yml
    with:
      rime_plugins: rime/librime-charcode hchunhui/librime-lua lotem/librime-octagram lotem/librime-proto

  release:
    needs: [macos, windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Create GitHub release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: ${{ contains(github.ref_name, '-') }}
          title: librime ${{ github.ref_name }}
          files: |
            artifact/*
