name: release ci
on:
  push:
    tags:
      - "*"
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++, clang]
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Install dependency
        run: ./action-install-linux.sh

      - name: Unit test
        run: make test
  macos:
    runs-on: macos-latest
    env:
      boost_version: 1.75.0
      BOOST_ROOT: ${{ github.workspace }}/thirdparty/src/boost_1_75_0
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Cache Boost
        id: cache-boost
        uses: actions/cache@v2
        with:
          path: ${{ env.BOOST_ROOT }}
          key: ${{ runner.os }}-build-cache-boost-${{ env.boost_version }}

      - name: Install Boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        run: make xcode/thirdparty/boost

      - name: Check submodules
        run: git submodule > submodule-status

      - name: Cache thirdparty
        id: cache-thirdparty
        uses: actions/cache@v2
        with:
          path: |
            thirdparty/bin
            thirdparty/include
            thirdparty/lib
            thirdparty/share
          key: ${{ runner.os }}-build-cache-thirdparty-${{ hashFiles('submodule-status') }}

      - name: Build thirdparty
        if: steps.cache-thirdparty.outputs.cache-hit != 'true'
        run: make xcode/thirdparty

      - name: Install Rime plugins
        run: ./action-install-plugins-macos.sh

      - name: Unit test
        run: make xcode/test

      - name: Upload artifactory
        run: |
          make xcode/dist
          echo TODO
  windows:
    runs-on: windows-latest
    env:
      boost_version: 1.76.0
      BOOST_ROOT: ${{ github.workspace }}/thirdparty/src/boost_1_76_0
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Cache Boost
        id: cache-boost
        uses: actions/cache@v2
        with:
          path: ${{ env.BOOST_ROOT }}
          key: ${{ runner.os }}-build-cache-boost-${{ env.boost_version }}

      - name: Install Boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        run: .\install-boost.bat

      - name: Check submodules
        run: git submodule > submodule-status

      - name: Cache thirdparty
        id: cache-thirdparty
        uses: actions/cache@v2
        with:
          path: |
            thirdparty/bin
            thirdparty/include
            thirdparty/lib
            thirdparty/share
          key: ${{ runner.os }}-build-cache-thirdparty-${{ hashFiles('submodule-status') }}

      - name: Build thirdparty
        if: steps.cache-thirdparty.outputs.cache-hit != 'true'
        run: .\build.bat thirdparty

      - name: Install Rime plugins
        run: .\action-install-plugins-windows.bat

      - name: Unit test
        run: .\build.bat test

      - name: Upload artifactory
        run: echo TODO
